language: python

python:
  - "2.7"

services:
  - mysql

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get purge -y mysql-common
  - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
  - sudo python install.py --develop --user travis --mysql-root-password travis --without-bench-setup
  - sudo pip install --upgrade pip
  - sudo pip install -e ~/bench
  - rm $TRAVIS_BUILD_DIR/.git/shallow
  - cd ~/ && bench init frappe-bench
  - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/


script:
  - cd ~/frappe-bench
  - bench get-app erpnext https://github.com/frappe/erpnext.git --branch master
  - bench get-app fimax https://github.com/YefriTavarez/fimax.git --branch master
  - bench use test_site
  - bench reinstall
  - bench --site test_site install-app erpnext
  - bench --site test_site install-app fimax
  - bench start &
  - sleep 10
  - bench --verbose run-tests --driver Firefox

before_script:
  - mysql -e 'create database test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis
