language: python
dist: trusty

python:
  - "2.7"

services:
  - mysql

before_script:
  - mysql -u root -ptravis -e 'CREATE DATABASE test_frappe'
  - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis

#  - cd ~/frappe-bench
#  - bench use test_site
#  - bench reinstall --yes
#  - bench setup-help
#  - bench scheduler disable
#  - bench start &
#  - sleep 20

install:
  - sudo rm /etc/apt/sources.list.d/mongodb*.list
  - sudo rm /etc/apt/sources.list.d/docker.list
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - nvm install v8.10.0
